layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: '' # an empty string here means all files in the project
      type: 'posts'
    values:
      layout: 'post'

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: true
    forks: true
    projects:
      - template-unity

social_media:
  stackoverflow: 4187549
  linkedin: FurkanKambay

topics:
  - name: C#
    web_url: https://github.com/topics/csharp
    image_url: ./assets/logos/csharp.png

  - name: .NET
    web_url: https://github.com/topics/dotnet
    image_url: ./assets/logos/dotnet.png

  - name: Git
    web_url: https://github.com/topics/git
    image_url: ./assets/logos/git.png

  - name: Unity
    web_url: https://github.com/topics/unity
    image_url: ./assets/logos/unity.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: ./assets/logos/python.png

  - name: Blender
    web_url: https://github.com/topics/blender
    image_url: ./assets/logos/blender.png

  - name: Electronics
    web_url: https://github.com/topics/electronics

  - name: Hacking
    web_url: https://github.com/topics/hacking

  - name: XAML
    web_url: https://github.com/topics/xaml

  - name: RegEx
    web_url: https://github.com/topics/regex
