baseURL = "https://furkankambay.com"
languageCode = "en-us"
theme = "awesome-identity"
disableKinds = ["taxonomy", "term"]
title = "Furkan Kambay - Software Engineer"

[params.profile]
  portrait = "/images/whoami.png"
  firstname = "Furkan"
  lastname = "Kambay"
  title = "Software Engineer"
  bio = """
  I am a self-taught software developer mostly experienced in C#, C++, and Python.
  I care about writing clean and self-documenting code.
  
  Recently, I am very interested in Unity game development
  and I try to work on some of my ideas when I have time.
  
  I am also a beginner in penetration testing, reverse engineering, and electronics.
  """

[params.contacts]
  github = "FurkanKambay"
  gitlab = "FurkanKambay"
  hackthebox = "122166"
  linkedin = "FurkanKambay"
  stackoverflow = "4187549"

[params.actions.source]
  name = "Site Source"
  url = "https://github.com/FurkanKambay/furkankambay.github.io"

[params.footer]
  poweredBy = true
